function [y, info] = shc_to_binaural(shc)
%SHC_TO_BINAURAL Binaural rendering from spherical-harmonics (HOA) channels using built-in default BRIRs.
%
%   [y, info] = shc_to_binaural(shc)
%
% This function takes an audio signal encoded in Spherical Harmonics Coefficients (SHC)
% up to order N (Higher-Order Ambisonics / HOA) and produces a 2-channel binaural
% signal [Left Right]. **No external HRIR/BRIR files are needed**: a small synthetic
% default binaural room impulse response (BRIR) set is generated internally, projected
% into the SH domain, and cached for re-use.
%
% INPUT (single argument)
%   shc : Either
%         (A) numeric matrix containing SH channels:
%               - [Nsamples x C]  (preferred) OR [C x Nsamples]
%             where C = (N+1)^2.
%         OR
%         (B) struct with fields (first match wins):
%               .X, .shc, .data  : SH channel matrix as above
%               .Fs              : sampling rate in Hz (optional; default 48000)
%
% OUTPUTS
%   y    : Binaural output [Nsamples x 2] (same length as input by default).
%   info : Struct with debug/trace information:
%          .Fs, .N, .C, .method, .Lh, .M, .reg, .convention, .notes
%
% DEFAULTS / ASSUMPTIONS (IMPORTANT)
%   - Sample rate: 48 kHz unless shc is a struct with .Fs.
%   - SH convention: ACN channel ordering + N3D normalization (real SH basis).
%   - Output length: "same" as input (centered like conv(...,'same')).
%   - Decoder generation: synthetic BRIRs (simple ITD/ILD + mild reverberant tail),
%     then weighted least-squares per frequency bin (Tikhonov regularization).
%
% WHAT THIS IS / IS NOT
%   - This is a *self-contained* binaural renderer useful for testing pipelines when
%     you don't want to ship or depend on external SOFA/HRIR datasets.
%   - The default BRIRs are **not** perceptually accurate HRTFs. For real binaural
%     rendering, replace the synthetic BRIR generator with measured HRIR/BRIR data.
%
% EXAMPLE
%   % X is [Ns x C] where C=(N+1)^2 in ACN/N3D
%   y = shc_to_binaural(X);
%   soundsc(y, 48000);
%
% Author: Generated by ChatGPT
% -------------------------------------------------------------------------

% -------------------------
% 1) Parse input and layout
% -------------------------

[X, Fs] = local_parse_single_input(shc);

% Ensure floating point for predictable FFT behavior
if ~isfloat(X)
    X = double(X);
end

% Try to interpret layout and enforce [Ns x C]
X = local_ensure_Ns_by_C(X);

[Ns, C] = size(X);

% Infer HOA order from C = (N+1)^2
Norder = sqrt(C) - 1;
if abs(Norder - round(Norder)) > 1e-12 || Norder < 0
    error('shc_to_binaural:InvalidChannelCount', ...
        'Invalid channel count C=%d. Expected C=(N+1)^2.', C);
end
Norder = round(Norder);

% -----------------------------------------
% 2) Build / reuse default binaural decoder
% -----------------------------------------

% Cache decoded filters per (Norder, Fs) to avoid recomputing heavy steps.
persistent CACHE
if isempty(CACHE)
    CACHE = struct('N', {}, 'Fs', {}, 'Lh', {}, 'M', {}, 'reg', {}, ...
                   'hL', {}, 'hR', {}, 'meta', {});
end

% --- Internal "tunable" defaults (edit here if you want different behavior) ---
cfg = struct();
cfg.Fs              = Fs;        % sample rate
cfg.Lh              = 2048;      % filter length in samples (~42.7 ms at 48 kHz)
cfg.M               = max(240, 6*C);  % number of synthetic BRIR directions
cfg.reg             = 1e-6;      % Tikhonov regularization for LS inversion
cfg.blockLen        = 4096;      % overlap-save block length (new samples per block)
cfg.outMode         = 'same';    % 'same' keeps output length == input length
cfg.shConvention    = 'ACN-N3D'; % documented convention of the basis used here
cfg.verbose         = false;     % set true for console prints (keep false by default)
% ---------------------------------------------------------------------------

[dec, meta] = local_get_or_build_decoder(CACHE, Norder, cfg);

% Save back (MATLAB persistent structs are copy-on-write; assign explicitly)
CACHE = local_update_cache(CACHE, Norder, Fs, cfg, dec, meta);

% -----------------------------------------
% 3) Render to binaural (overlap-save FFT)
% -----------------------------------------

% NOTE: We always use overlap-save FFT for robustness and speed.
%       (Time-domain conv would be much slower for moderate N, Ns, Lh.)
[yL, yR] = local_ols_binaural_sum(X, dec.hL, dec.hR, cfg.blockLen);

% Stack stereo
yFull = [yL(:), yR(:)];

% -----------------------------------------
% 4) Output mode and optional safety scaling
% -----------------------------------------

switch lower(cfg.outMode)
    case 'full'
        y = yFull;
    case 'same'
        % Centered "same" crop to match input length (like conv(...,'same')).
        startIdx = floor((cfg.Lh - 1)/2) + 1;
        stopIdx  = startIdx + Ns - 1;
        y = yFull(startIdx:stopIdx, :);
    otherwise
        error('shc_to_binaural:BadOutMode', 'Internal cfg.outMode must be ''full'' or ''same''.');
end

% -------------------------
% 5) Collect debug metadata
% -------------------------

info = struct();
info.Fs         = Fs;
info.N          = Norder;
info.C          = C;
info.method     = 'fft-ols';
info.Lh         = cfg.Lh;
info.M          = cfg.M;
info.reg        = cfg.reg;
info.convention = cfg.shConvention;
info.notes      = meta.notes;

end % shc_to_binaural

% =========================================================================
% Local helper: parse the single input argument
% =========================================================================
function [X, Fs] = local_parse_single_input(shc)
%LOCAL_PARSE_SINGLE_INPUT Accept numeric matrix or struct with optional Fs.

FsDefault = 48000;

if isstruct(shc)
    % Pick first matching field for the signal matrix
    if isfield(shc, 'X')
        X = shc.X;
    elseif isfield(shc, 'shc')
        X = shc.shc;
    elseif isfield(shc, 'data')
        X = shc.data;
    else
        error('shc_to_binaural:BadStruct', ...
            'Struct input must contain .X, .shc, or .data for the SH signal.');
    end

    % Optional sample rate
    if isfield(shc, 'Fs') && ~isempty(shc.Fs)
        Fs = shc.Fs;
    else
        Fs = FsDefault;
    end
else
    X  = shc;
    Fs = FsDefault;
end

validateattributes(Fs, {'numeric'}, {'scalar','real','finite','positive'}, mfilename, 'Fs');

end

% =========================================================================
% Local helper: enforce [Nsamples x C] layout robustly
% =========================================================================
function X = local_ensure_Ns_by_C(X)
%LOCAL_ENSURE_NS_BY_C Attempt to orient X as [Ns x C].
%
% Heuristic:
%   - If one dimension is a perfect square, that dimension is likely C.
%   - Otherwise assume the common convention [Ns x C].

if ndims(X) ~= 2
    error('shc_to_binaural:BadInputShape', 'Input SH signal must be a 2-D matrix.');
end

s1 = size(X,1);
s2 = size(X,2);

isSq1 = (round(sqrt(s1))^2 == s1);
isSq2 = (round(sqrt(s2))^2 == s2);

if isSq1 && ~isSq2
    % Likely [C x Ns] -> transpose
    X = X.';
elseif ~isSq1 && isSq2
    % Likely [Ns x C] -> keep
else
    % Ambiguous -> keep as [Ns x C] (most common)
end

end

% =========================================================================
% Local helper: get cached decoder or build a new one
% =========================================================================
function [dec, meta] = local_get_or_build_decoder(CACHE, Norder, cfg)
%LOCAL_GET_OR_BUILD_DECODER Look up decoder in persistent CACHE or build it.

dec = struct('hL', [], 'hR', []);
meta = struct('notes', '');

% 1) Search cache
for k = 1:numel(CACHE)
    if CACHE(k).N == Norder && CACHE(k).Fs == cfg.Fs && CACHE(k).Lh == cfg.Lh
        dec.hL = CACHE(k).hL;
        dec.hR = CACHE(k).hR;
        meta   = CACHE(k).meta;
        return;
    end
end

% 2) Build new decoder
[IR, az, el, w] = local_generate_default_brir_set(cfg.Fs, cfg.Lh, cfg.M);

% 2a) Build real SH matrix (ACN, N3D) at the measurement directions
Y = local_real_sh_matrix_acn(az, el, Norder, 'N3D');  % [M x C]

% 2b) Compute SH-domain decoding filters (one set per ear)
[hL, hR] = local_brirset_to_sh_decoder(IR, Y, w, cfg.reg);

dec.hL = hL;
dec.hR = hR;

meta.notes = sprintf([ ...
    'Default decoder generated internally. Synthetic BRIR set: M=%d points (Fibonacci sphere), ' ...
    'Lh=%d samples. Basis: real SH, ACN ordering, N3D normalization.'], cfg.M, cfg.Lh);

end

% =========================================================================
% Local helper: update cache
% =========================================================================
function CACHE = local_update_cache(CACHE, Norder, Fs, cfg, dec, meta)
%LOCAL_UPDATE_CACHE Store decoder in cache if not already present.

% Check if already stored (avoid duplicates)
for k = 1:numel(CACHE)
    if CACHE(k).N == Norder && CACHE(k).Fs == Fs && CACHE(k).Lh == cfg.Lh
        CACHE(k).hL   = dec.hL;
        CACHE(k).hR   = dec.hR;
        CACHE(k).meta = meta;
        return;
    end
end

% Append new entry
entry = struct();
entry.N    = Norder;
entry.Fs   = Fs;
entry.Lh   = cfg.Lh;
entry.M    = cfg.M;
entry.reg  = cfg.reg;
entry.hL   = dec.hL;
entry.hR   = dec.hR;
entry.meta = meta;

CACHE(end+1) = entry; %#ok<AGROW>

end

% =========================================================================
% Local helper: generate a synthetic default BRIR set
% =========================================================================
function [IR, az, el, w] = local_generate_default_brir_set(Fs, Lh, M)
%LOCAL_GENERATE_DEFAULT_BRIR_SET Create simple, deterministic synthetic BRIRs.
%
% IR: [Lh x M x 2] where (:,:,1)=Left ear, (:,:,2)=Right ear
% az, el in radians.

% Deterministic randomness for the diffuse late tail (ensures reproducibility)
rng(0, 'twister');

% Uniform directions on the sphere (Fibonacci)
[az, el] = local_fibonacci_sphere_dirs(M);

% Equal-area weights (approx) for uniform sphere sampling
w = (4*pi / M) * ones(M, 1);

% Physical-ish constants for a crude ITD model
c = 343;       % speed of sound [m/s]
r = 0.0875;    % head radius [m] (approx)

% Room-ish parameters for a mild reverberant tail
tailStart_s = 0.020;     % when late tail begins
tau_s       = 0.050;     % exponential decay time constant
tailGain    = 0.03;      % overall late tail level

% Early reflections (simple, same for both ears but scaled by ear gain)
refDelays_s = [0.010, 0.018, 0.027];     % reflection delays
refGains    = [0.20, 0.12, 0.07];        % reflection gains

% Allocate IRs
IR = zeros(Lh, M, 2);

% Precompute indices
n0 = max(1, round(0.001 * Fs));  % direct path nominal time (1 ms)

% For each direction, create left/right impulse responses
for m = 1:M
    azi = az(m);%+pi/2;

    % --- 1) ITD (Woodworth-style approximation; good enough for a synthetic default) ---
    % Use absolute azimuth in [0, pi]
    a = abs(azi);
    if a <= pi/2
        itd = (r/c) * (a + sin(a));
    else
        itd = (r/c) * (pi - a + sin(a));
    end
    dSamp = max(0, round(itd * Fs)); % integer sample difference

    % --- 2) ILD (simple azimuth-dependent gain) ---
    ildMax_dB = 10;                % max ILD at +/-90 deg (very rough)
    ild_dB    = ildMax_dB * sin(azi);
    gL = 10^(+ild_dB/20);
    gR = 10^(-ild_dB/20);

    % Decide which ear is "near" (earlier arrival)
    if azi >= 0
        % Source on left side -> left ear earlier
        idxL = n0;
        idxR = min(Lh, n0 + dSamp);
        nearIsLeft = true;
    else
        idxR = n0;
        idxL = min(Lh, n0 + dSamp);
        nearIsLeft = false;
    end

    hL = zeros(Lh,1);
    hR = zeros(Lh,1);

    % Direct sound
    hL(idxL) = hL(idxL) + gL;
    hR(idxR) = hR(idxR) + gR;

    % Early reflections (same delays, scaled by ear gains)
    for k = 1:numel(refDelays_s)
        dk = round(refDelays_s(k) * Fs);
        iL = min(Lh, idxL + dk);
        iR = min(Lh, idxR + dk);
        hL(iL) = hL(iL) + refGains(k) * gL;
        hR(iR) = hR(iR) + refGains(k) * gR;
    end

    % Late reverberant tail (diffuse-ish, same *statistics* both ears, scaled)
    tailStart = min(Lh, round(tailStart_s * Fs));
    if tailStart < Lh
        n = (tailStart:Lh).';
        env = exp(-(n - tailStart) / max(1, round(tau_s * Fs)));
        noiseL = randn(numel(n),1);
        noiseR = randn(numel(n),1);

        hL(tailStart:Lh) = hL(tailStart:Lh) + tailGain * gL * (noiseL .* env);
        hR(tailStart:Lh) = hR(tailStart:Lh) + tailGain * gR * (noiseR .* env);
    end

    % --- 3) Crude spectral shaping (shadowing) using 1st-order IIR LPF impulse response ---
    % Near ear: high cutoff, Far ear: lower cutoff depending on lateral angle.
    lat = abs(sin(azi)); % 0 front/back, 1 at +/-90 deg
    fcNear = 18000;      % Hz
    fcFar  = 6000 + (1-lat)*6000;  % 6..12 kHz (rough shadowing)

    if nearIsLeft
        hL = local_apply_1pole_lpf_to_ir(hL, Fs, fcNear);
        hR = local_apply_1pole_lpf_to_ir(hR, Fs, fcFar);
    else
        hR = local_apply_1pole_lpf_to_ir(hR, Fs, fcNear);
        hL = local_apply_1pole_lpf_to_ir(hL, Fs, fcFar);
    end

    IR(:,m,1) = hL;
    IR(:,m,2) = hR;
end

end

% =========================================================================
% Local helper: apply a 1-pole IIR low-pass to an impulse response and truncate
% =========================================================================
function hOut = local_apply_1pole_lpf_to_ir(hIn, Fs, fc)
%LOCAL_APPLY_1POLE_LPF_TO_IR Filter an impulse response with a simple one-pole LPF.
%
% We use the standard smoothing form:
%   y[n] = (1-a)*x[n] + a*y[n-1]
% where a = exp(-2*pi*fc/Fs).
%
% For an impulse response input, this yields the impulse response of the IIR.
% We apply it here to introduce a crude, deterministic "shadowing" effect.

fc = max(50, min(fc, 0.45*Fs));   % clamp to a reasonable range
a  = exp(-2*pi*fc/Fs);

b0 = (1 - a);
a1 = -a;

% filter(b, a, x) with a = [1, a1]
hOut = filter(b0, [1, a1], hIn);

end

% =========================================================================
% Local helper: Fibonacci sphere directions (azimuth/elevation)
% =========================================================================
function [az, el] = local_fibonacci_sphere_dirs(M)
%LOCAL_FIBONACCI_SPHERE_DIRS Generate quasi-uniform directions over the sphere.
%
% Returns azimuth az in [-pi, pi], elevation el in [-pi/2, pi/2].

k = (0:M-1).';

% z from +1 to -1 (equal area)
z = 1 - 2*(k + 0.5)/M;

% golden angle increment
golden = (1 + sqrt(5)) / 2;
az = 2*pi * (k / golden);

r = sqrt(max(0, 1 - z.^2));

x = r .* cos(az);
y = r .* sin(az);

az = atan2(y, x);   % [-pi, pi]
el = asin(z);       % [-pi/2, pi/2]

end

% =========================================================================
% Local helper: Real SH matrix, ACN ordering, N3D/SN3D normalization
% =========================================================================
function Y = local_real_sh_matrix_acn(az, el, Norder, normType)
%LOCAL_REAL_SH_MATRIX_ACN Compute real spherical harmonics (ACN ordering).
%
% Inputs:
%   az, el : Mx1 in radians (azimuth, elevation)
%   Norder : maximum SH order N
%   normType : 'N3D' or 'SN3D'
%
% Output:
%   Y : [M x C] where C=(N+1)^2 and columns follow ACN index:
%       n = l(l+1) + m,  with m in [-l, l], n in [0..C-1]

az = az(:);
el = el(:);
M = numel(az);
C = (Norder+1)^2;

% Convert to colatitude theta
theta = pi/2 - el;           % theta in [0..pi]
ct = cos(theta);             % cos(theta)

Y = zeros(M, C);

% Loop over degrees and orders
for l = 0:Norder
    % Associated Legendre functions P_l^m(ct) for m>=0 returned by legendre:
    %   Plm has size (m+1) x M.
    Plm = legendre(l, ct.', 'sch');  % Schmidt semi-normalized by default
    % NOTE:
    %  MATLAB's 'sch' output is Schmidt semi-normalized. We'll convert to our
    %  desired normalization explicitly via scaling factors below.
    %
    %  We use this approach because it is numerically stable.
    %
    %  Conversion factors:
    %   Schmidt semi-normalized -> unnormalized is known; but rather than deriving
    %   two conversions, we directly compute the target normalization constant
    %   and apply it to the *unnormalized* P_l^m. Since we have 'sch', we undo it.
    %
    %  For simplicity and robustness here, we reconstruct an effective P using
    %  MATLAB's 'sch' and incorporate correction into the normalization factor.
    %
    %  This decoder is synthetic; the exact scaling is less critical than consistency.

    for m = -l:l
        n = l*(l+1) + m;   % ACN
        idx = n + 1;       % MATLAB 1-based

        mm = abs(m);

        % Extract Schmidt semi-normalized associated Legendre
        Psch = squeeze(Plm(mm+1, :)).';  % [M x 1]

        % Base (complex) normalization constant for N3D
        %   N3D:  sqrt((2l+1)/(4pi) * (l-m)!/(l+m)!)
        %   SN3D: sqrt(1/(4pi)         * (l-m)!/(l+m)!)
        %
        % Then for real SH we apply sqrt(2) for m != 0.
        if strcmpi(normType, 'N3D')
            K = sqrt((2*l + 1)/(4*pi) * factorial(l-mm)/factorial(l+mm));
        elseif strcmpi(normType, 'SN3D')
            K = sqrt(1/(4*pi) * factorial(l-mm)/factorial(l+mm));
        else
            error('shc_to_binaural:BadNorm', 'normType must be ''N3D'' or ''SN3D''.');
        end

        % Schmidt semi-normalization factor (for m>0):
        % Schmidt: Psch = sqrt(2*(l-m)!/(l+m)!) * P (for m>0), and Psch = P for m=0.
        % This is a common convention; MATLAB's 'sch' follows Schmidt semi-normalized.
        % So to approximate the unnormalized P, we divide by that factor.
        if mm == 0
            P = Psch;
            schFactor = 1;
        else
            schFactor = sqrt(2 * factorial(l-mm)/factorial(l+mm));
            P = Psch / schFactor;
        end

        if m == 0
            % Y_{l,0} = K * P_l^0(cos theta)
            Y(:, idx) = K * P;
        elseif m > 0
            % Y_{l,m}^real = sqrt(2) * K * P_l^m(cos theta) * cos(m*az)
            Y(:, idx) = sqrt(2) * K * P .* cos(mm * az);
        else
            % Y_{l,-m}^real = sqrt(2) * K * P_l^m(cos theta) * sin(m*az)
            Y(:, idx) = sqrt(2) * K * P .* sin(mm * az);
        end
    end
end

end

% =========================================================================
% Local helper: convert a BRIR set into SH-domain decoding filters
% =========================================================================
function [hL, hR] = local_brirset_to_sh_decoder(IR, Y, w, reg)
%LOCAL_BRIRSET_TO_SH_DECODER Compute SH-domain binaural decoder filters.
%
% Inputs:
%   IR : [Lh x M x 2] BRIRs at M directions for left/right ear
%   Y  : [M x C] real SH matrix evaluated at the same directions
%   w  : [M x 1] nonnegative weights (sphere sampling weights)
%   reg: scalar Tikhonov regularization strength
%
% Outputs:
%   hL, hR : [Lh x C] time-domain FIR filters (one per SH channel)

[Lh, M, E] = size(IR);
if E ~= 2
    error('shc_to_binaural:BadIR', 'IR must be [Lh x M x 2].');
end
if size(Y,1) ~= M
    error('shc_to_binaural:BadShapes', 'Y must be [M x C] consistent with IR directions.');
end

C = size(Y,2);

w = w(:);
if numel(w) ~= M
    error('shc_to_binaural:BadWeights', 'w must be length M.');
end

% Weighted LS matrices
sqrtw = sqrt(max(w, 0));
Yw = Y .* sqrtw;           % [M x C] (implicit broadcasting)
A  = (Yw.' * Yw) + reg * eye(C);  % [C x C] stable normal matrix

% FFT size (use power-of-two for speed)
Nfft = 2^nextpow2(Lh);

% FFT of IRs across time
HL = fft(IR(:,:,1), Nfft, 1);  % [Nfft x M]
HR = fft(IR(:,:,2), Nfft, 1);  % [Nfft x M]

K = floor(Nfft/2) + 1;         % positive-frequency bins (including DC/Nyquist)

WL = zeros(K, C);              % [K x C] positive spectrum for left
WR = zeros(K, C);

% Precompute transpose for speed/readability
YwT = Yw.';                    % [C x M]

for k = 1:K
    % Extract frequency responses across directions for this bin
    HkL = HL(k,:).';           % [M x 1]
    HkR = HR(k,:).';

    % Apply weights in the observation vector
    HkLw = sqrtw .* HkL;
    HkRw = sqrtw .* HkR;

    % Solve normal equations:
    %   Wk = (Yw^T Yw + reg I)^{-1} (Yw^T Hk_w)
    %
    % Result is Cx1 (filters for each SH channel at this frequency).
    wkL = A \ (YwT * HkLw);
    wkR = A \ (YwT * HkRw);

    WL(k,:) = wkL.';
    WR(k,:) = wkR.';
end

% Build full conjugate-symmetric spectra to obtain real-valued FIRs
WLfull = zeros(Nfft, C);
WRfull = zeros(Nfft, C);

WLfull(1:K,:) = WL;
WRfull(1:K,:) = WR;

% Mirror bins (exclude DC=1 and Nyquist=K when even Nfft)
if Nfft > 1
    WLfull(K+1:end,:) = conj(WL(end-1:-1:2,:));
    WRfull(K+1:end,:) = conj(WR(end-1:-1:2,:));
end

% Time-domain filters
hL0 = real(ifft(WLfull, Nfft, 1));
hR0 = real(ifft(WRfull, Nfft, 1));

% Truncate and apply a gentle fade-out to reduce circular/FFT artifacts
hL = hL0(1:Lh, :);
hR = hR0(1:Lh, :);

nFade = min(256, max(32, round(0.10 * Lh)));  % ~10% fade, clamped
win = ones(Lh, 1);
t = (0:nFade-1).';
win(end-nFade+1:end) = 0.5 * (1 + cos(pi * t / (nFade-1))); % half-cosine to 0

hL = hL .* win;
hR = hR .* win;

end

% =========================================================================
% Local helper: overlap-save binaural rendering with SH summation
% =========================================================================
function [yL, yR] = local_ols_binaural_sum(X, hL, hR, blockLen)
%LOCAL_OLS_BINAURAL_SUM Efficiently compute:
%   yL = sum_c X_c (*) hL_c
%   yR = sum_c X_c (*) hR_c
% where (*) is linear convolution.

[Ns, C] = size(X);
[Lh, C2] = size(hL);

if C2 ~= C || ~isequal(size(hR), [Lh, C])
    error('shc_to_binaural:DecoderMismatch', 'Decoder filters must be [Lh x C].');
end

% Overlap-save parameters
M = Lh;
L = max(256, round(blockLen));
if L <= M
    L = M + 256;
end
Nfft = 2^nextpow2(L + M - 1);
Hop  = L;              % how many new samples per iteration
Ovl  = M - 1;          % overlap length

% Precompute FFT of filters
HL = fft(hL, Nfft, 1); % [Nfft x C]
HR = fft(hR, Nfft, 1); % [Nfft x C]

% Pad input with overlap zeros
xPad = [zeros(Ovl, C); X];
nPad = size(xPad, 1);

% Full convolution length
Ny = Ns + M - 1;
yL = zeros(Ny, 1);
yR = zeros(Ny, 1);

outWritePos = 1;
start = 1;

while start <= nPad
    stop = start + (L + Ovl) - 1;

    % Extract block with zero-padding at end
    if stop <= nPad
        xBlk = xPad(start:stop, :);
    else
        xBlk = [xPad(start:end, :); zeros(stop - nPad, C)];
    end

    % FFT of block
    Xf = fft(xBlk, Nfft, 1);

    % Multiply-and-sum across SH channels
    YLf = sum(Xf .* HL, 2);
    YRf = sum(Xf .* HR, 2);

    % Back to time
    yBlkL = real(ifft(YLf, Nfft, 1));
    yBlkR = real(ifft(YRf, Nfft, 1));

    % Overlap-save discard
    yValidL = yBlkL(Ovl+1:Ovl+L);
    yValidR = yBlkR(Ovl+1:Ovl+L);

    % Write into output
    writeStop = min(outWritePos + L - 1, Ny);
    nToWrite  = writeStop - outWritePos + 1;

    yL(outWritePos:writeStop) = yL(outWritePos:writeStop) + yValidL(1:nToWrite);
    yR(outWritePos:writeStop) = yR(outWritePos:writeStop) + yValidR(1:nToWrite);

    % Advance
    outWritePos = outWritePos + Hop;
    start = start + Hop;

    if outWritePos > Ny
        break;
    end
end

end
